//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_Toy_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoZamowione
    {
        public int Id { get; set; }
        public string Id_zamowienia { get; set; }
        public int Id_produktu { get; set; }
        public string e_mail { get; set; }
    }
}
