//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_Toy_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public string Id_uzytkownik { get; set; }
        public string imie { get; set; }
        public string email { get; set; }
        public string nazwisko { get; set; }
        public string ulica { get; set; }
        public string numer_domu { get; set; }
        public string kod_pocztowy { get; set; }
        public string poczta { get; set; }
    }
}
