//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_Toy_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentarze
    {
        public int Id_koment { get; set; }
        public Nullable<System.DateTime> data_dodania { get; set; }
        public string id_uzytkownika { get; set; }
        public int id_produktu { get; set; }
        public string koment { get; set; }
        public Nullable<int> ocena { get; set; }
        public string e_mail { get; set; }
    }
}
