//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_Toy_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int Id_produktu { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public double cena { get; set; }
        public string obrazek { get; set; }
        public Nullable<int> dozw_wiek { get; set; }
        public Nullable<int> rok_produkcji { get; set; }
    }
}
