//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childrens_Toy_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamowienia
    {
        public string Id_zamowienia { get; set; }
        public Nullable<System.DateTime> data_wyslania { get; set; }
        public string id_klienta { get; set; }
        public string e_mail { get; set; }
        public Nullable<int> status { get; set; }
        public string id_pracownika { get; set; }
        public string ad_wysylki { get; set; }
    }
}
